economy/__init__.py
#===============================================================================
# 项目初始化
#===============================================================================
from flask import Flask
from economy.views import viewManager 
from flask_pymongo import PyMongo

# 初始化PyMongo
mongodb = PyMongo()

# 初始化系统
def initSystem():
    global mongodb
    
    # 初始化Flask对象
    sys = Flask(__name__)
    # 注册配置文件
    sys.config.from_object('economy.secure')    
    sys.config.from_object('economy.setting') 
    
    # 注册蓝图管理路由系统
    sys.register_blueprint(viewManager) 
    
    # 注册MongoDB
    sys.config["MONGO_URI"] = 'mongodb://192.168.0.180:27017/db_finance'
    
    mongodb.init_app(sys)
    
    # 使用进程打开窗口，向用户展示
    return sys















































































economy/views/__init__.py
#===============================================================================
# 蓝图初始化
#===============================================================================
from flask import Blueprint, render_template

# 蓝图blueprint:用于解决视图函数与app的绑定问题,用一个蓝图管理多个不同的视图函数
viewManager = Blueprint('viewManager', __name__)
# web = Blueprint('web', __name__, template_folder='templates')# 这里的蓝图也可以注册静态文件static_folder='', static_url_path=''

#-- 分别导入蓝图管理的所有视图函数文件 ---------------------------------------------------------------------------- 
from economy.views import url


# 导入macroData的路由
from economy.views.front import frontUrl
from economy.views.front.macroData import macroData
from economy.views.front.info import info



#----- 后台URL管理 ------------------------------------------------------------------------- 
from economy.views.back import backUrl
from economy.views.back.info import info














































































































economy/views/test.py
#===============================================================================
# 系统架构测试
#===============================================================================
from flask import jsonify, request, render_template,flash
from . import viewManager


# 主页
@viewManager.route('/')
def index():
    return render_template("index.html")

# 跳转后台
@viewManager.route('/toBackIndex')
def toBackIndex():
    return render_template("back_index.html")







































































economy/views/url.py
#===============================================================================
# 系统架构测试
#===============================================================================
from flask import jsonify, request, render_template,flash
from . import viewManager
import json
from economy.xiaoBing.voice import Speech



speech = Speech()
def speak(str):
    xiaoBing = speech.syntheticSpeech(str) 
    return xiaoBing


# 主页
@viewManager.route('/')
def index():
#     xiaoBing = speech.syntheticSpeech("主人，你终于来到经济系统了！这里有有关经济的一切，您有什么需要尽管跟我说。") 


    data = {}
    return render_template("front/index.html",data=data)


# 语音小冰
@viewManager.route("/toXiaoBing", methods=['POST'])
def toXiaoBing():
    if request.method == 'POST':
        data = json.loads(request.get_data().decode("UTF-8"))
        res = None
        if data["flag"] == "macroData":
#             xiaoBing =speak("今年国家的数据比较良好，目前市场趋于稳定，建议购买一点国债！")
            res = {}
#             res = {"data": xiaoBing}
    return json.dumps(res)





































































economy/templates/back/index.html
<html>
<head>
    <title>后台系统</title>
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='back/index/css/index.css')}}"/>
    <script type="text/javascript" src="{{url_for('static', filename='sys/js/jquery-2.0.0.min.js')}}"></script>
    <script type="text/javascript" src="{{url_for('static', filename='back/index/js/index.js')}}"></script>
</head>
<body>
	<div class="container">
        <div class="containerTop">
			<a href="{{url_for('viewManager.index')}}">返回前台</a>
        </div>
        
        <div class="containerLeft">
            <ul>
                <li class="li_1"><div class="imgCls"><img src="{{url_for('static', filename='back/index/img/data.png')}}"/></div></li>
               	<!-- 资讯管理 -->
                <li class="li_2" id="info"><div class="imgCls"><img src="{{url_for('static', filename='back/index/img/info.png')}}"/></div></li>
                <li class="li_3" id="setting"><div class="imgCls"><img src="{{url_for('static', filename='back/index/img/setting.png')}}"/></div></li>
                <li class="li_4"><div class="imgCls"><img src="{{url_for('static', filename='back/index/img/reposity.png')}}"/></div></li>
                <li class="li_5"><div class="imgCls"><img src="{{url_for('static', filename='back/index/img/reposity.png')}}"/></div></li>
            </ul>
        </div>
        
        <div class="containerRight">
            <div class="firstMenu">
                <ul>
                    <li class="addMenu">添加菜单</li>
                    <li class="hotNews">热点资讯</li>
                   	<li class="knowledge">知识库</li>
                </ul>
            </div>
			<iframe 
				class="iframe" 
				id="iframe" 
				src="" 
				width="100%" 
				height="100%"
				frameborder="0"
				scrolling="auto">
			</iframe>
        </div>
    </div>
</body>
</html>

economy/templates/back/info/hotNews.html
<html>
<head>
<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='back/info/hotNews/css/hotNews.css')}}"/>
<script type="text/javascript" src="{{url_for('static', filename='sys/js/jquery-2.0.0.min.js')}}"></script>
<script type="text/javascript" src="{{url_for('static', filename='back/info/hotNews/js/hotNews.js')}}"></script>
</head>
<body>
	<select class="targetWeb">
		<option selected value="sina">Sina</option>
		<option value="fengHuang">凤凰</option>
	</select>
	<select class="targetType">
		<option>点击总排行</option>
		<option>评论总排行</option>
	</select>
	
	<button class="search">搜索</button>
	
	
	<table class="table" id="table">
		<tr>
			<th></th>
		</tr>
		<!-- 
		{% for item in res%}
		<tr>
			<td>{{item.title}}</td>
			<td>{{item._id}}</td>
		</tr>
		{% endfor %}
		 -->
	</table>
</body>
</html>

economy/templates/back/info/info.html
{% extends 'layout.html' %}

{% block outRefer %}
<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='front/info/index/css/index.css')}}"/>
<script type="text/javascript" src="{{url_for('static', filename='sys/js/jquery-2.0.0.min.js')}}"></script>
<script type="text/javascript" src="{{url_for('static', filename='sys/js/echarts.min.js')}}"></script>
<script type="text/javascript" src="{{url_for('static', filename='front/info/index/js/index.js')}}"></script>
{% endblock %}

{% block view_main %}


<ul class="menu">
	<li class="li"><a href="{{url_for('viewManager.toHotNews')}}">测试</a></li>
	<li class="li">测试</li>
	<li class="li">测试</li>
	<li class="li">测试</li>
	<li class="li">测试</li>
</ul>	




{% endblock %}

economy/templates/back/login.html
<html>
<head>
    <title>后台登录</title>
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='sys/css/sys.css')}}"/>
    <script type="text/javascript" src="{{url_for('static', filename='sys/js/jquery-2.0.0.min.js')}}"></script>
    <script type="text/javascript" src="{{url_for('static', filename='sys/js/layout.js')}}"></script>
    
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='back/login/css/login.css')}}"/>
    <script type="text/javascript" src="{{url_for('static', filename='back/login/js/login.js')}}"></script>
</head>
<body>
   	<a href="{{url_for('viewManager.index')}}" class="returnIndex">返回</a>
	<div class="loginPanel">
	    <header>
	        <div>金融系统</div>
	        <div>金融系统</div>
	    </header>
	    <h1>{{voice}}</h1>
	    <section>
	        <table>
	            <tr>
	                <td class="info">用户名：</td>
	                <td><input type="text" name="username" placeholder="请输入你的用户名：" /></td>
	            </tr>
	            <tr>
	                <td class="info">密&nbsp;&nbsp;&nbsp;码：</td>
	                <td><input type="password" name="password" placeholder="请输入你的密码：" /></td>
	            </tr>
	            <tr>
	                <td colspan="2"><div class="loginBtn"><a href="{{url_for('viewManager.toBackIndex')}}">登&nbsp;&nbsp;陆</a></div></td>
	            </tr>
	        </table>
	    </section>
	</div>
</body>
</html>

economy/templates/back/setting/addSetting.html
<html>
<head>
<title>添加主菜单</title>
<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='back/info/hotNews/css/hotNews.css')}}"/>
<script type="text/javascript" src="{{url_for('static', filename='sys/js/jquery-2.0.0.min.js')}}"></script>
<script type="text/javascript" src="{{url_for('static', filename='back/info/hotNews/js/hotNews.js')}}"></script>
</head>
<body>
	<button>添加主菜单</button>
	<form action="/setting/addSetting" method="POST">
		<input type="text" placeholder="请输入主菜单名称"/>
		<input type="text" placeholder="制定图标的地址" />
		<input type="text" placeholder="请输入主菜单跳转的地址" />
	</form>
</body>
</html>

economy/templates/back_index.html
{% extends 'layout.html' %}


{% block outRefer %}
<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='index/css/index.css')}}"/>
{% endblock %}


<!-- 头部 -->
{% block view_header %}
	<a href="">资讯系统</a>
{% endblock %}


<!-- 左边工具栏 -->
{% block view_leftNav %}

{% endblock %}


<!-- 主内容 -->
{% block view_main %}

{% endblock %}


<!-- 右边工具栏 -->
{% block view_rightNav %}

{% endblock %}


<!-- 底部 -->
{% block view_footer %}

{% endblock %}
























































economy/templates/front/index.html
{% extends 'layout.html' %}

{% block outRefer %}
<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='front/index/css/index.css')}}"/>
<script type="text/javascript" src="{{url_for('static', filename='front/index/js/index.js')}}"></script>
{% endblock %}


<!-- 头部 -->
{% block view_header %}
<div class="view_header">
	<audio class="xiaoBing" id="xiaoBing" autoplay src="{{data.xiaoBing}}" preload="auto"></audio>
	<div class="logo">
		<img src="{{url_for('static',filename='front/index/img/logo.png')}}"/>	
	</div>
	<div class="headerRight">
		<a>待处理事务</a>
		<a>登陆 | 注册</a>
		<a>账户</a>
		<a href="{{url_for('viewManager.toBackIndex')}}">后台管理</a>
	</div>
</div>
{% endblock %}


<!-- 主内容 -->
{% block view_main %}
<div class="view_main">
	<!-- 左边工具栏 -->
	<div class="view_leftNav">
		<ul>
			<li class="li">
				<div class="imgWrapper macroData" id="index">
					<img class="img" src="{{url_for('static', filename='front/index/img/index.png')}}" alt="工作台"/>
				</div>	
			</li>
			<li class="li">
				<div class="imgWrapper macroData" id="macroData">
					<img class="img" src="{{url_for('static', filename='front/index/img/macroData.png')}}" alt="宏观经济"/>
				</div>	
			</li>
			<li class="li">
				<div class="imgWrapper macroData" id="info">
					<img class="img" src="{{url_for('static', filename='front/index/img/info.png')}}" alt="热点资讯"/>
				</div>	
			</li>
			<li class="li">
				<div class="imgWrapper macroData" id="stock">
					<img class="img" src="{{url_for('static', filename='front/index/img/stock.png')}}" alt="股票"/>
				</div>	
			</li>
		</ul>
	</div>
	<div class="view_content">
		<iframe 
			class="iframe" 
			id="iframe" 
			src="{{url_for('viewManager.toMacroData')}}" 
			width="100%" 
			height="100%"
			frameborder="0"
			scrolling="auto">
		</iframe>
		
		<!-- 热点新闻 -->
		<div class="newsTip">
			<div class="newHead">
				<h3 class="newsTipTitle">热点新闻</h3>
				<div class="closeIcon">
					<img class="img" src="{{url_for('static', filename='front/index/img/cancel.png')}}" alt="取消"/>
				</div>
			</div>
			<ul class="newLists"></ul><!-- 由JS控制 -->
			<div class="newsMore">更多>></div>
		</div>
		
	</div>
	<div class="view_rightNav">
		
	</div>
</div>
{% endblock %}



<!-- 底部 -->
{% block view_footer %}
<div class="view_footer">
	<div>今天天气良好，适合做秀秀的事情</div>
	<div class="currentTime"></div>
</div>
{% endblock %}
























































economy/templates/front/index/index.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<h1>工作台</h1>
</body>
</html>

economy/templates/front/info/info_index.html
{% extends 'layout.html' %}

{% block outRefer %}
<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='front/info/info_index/css/info_index.css')}}"/>
<script type="text/javascript" src="{{url_for('static', filename='front/info/info_index/js/info_index.js')}}"></script>
{% endblock %}

{% block view_main %}
<div class="top">
	<button>社会热点</button>
	<button>财经热点</button>
</div>
<div class="content">
	<table>
		<tr>
			<th>序号</th>
			<th>标题</th>
			<th>时间</th>
			<th>来源</th>
			<th>备注</th>
		</tr>
		{% for item in data.topNews %}
			<tr>
				<td width="300"><a href="{{item.href}}">{{item.title}}</a></td>
				<td>{{item.time}}</td>
			</tr>
		{% endfor %}
	</table>
</div>
{% endblock %}

economy/templates/front/macroData/gdp.html
{% extends 'layout.html' %}

{% block outRefer %}
<!-- 引入当前页面的css -->
<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='front/macroData/gdp/css/gdp.css')}}"/>
<script type="text/javascript" src="{{url_for('static', filename='sys/js/jquery-2.0.0.min.js')}}"></script>
<script type="text/javascript" src="{{url_for('static', filename='sys/js/echarts.min.js')}}"></script>
<script type="text/javascript" src="{{url_for('static', filename='front/macroData/gdp/js/gdp.js')}}"></script>
<script type="text/javascript" src="{{url_for('static', filename='front/macroData/gdp/js/world.js')}}"></script>
{% endblock %}

<!-- 主内容 -->
{% block view_main %}
<!--  
<div>
	<input type="text" class="country"/>
	<button class="queryCountry">查询</button>
</div>
-->

<div id="world" style="width:80%;height:80%;border:1px solid black;"></div>




{% endblock %}























































economy/templates/front/macroData/macroData.html
{% extends 'layout.html' %}

{% block outRefer %}
<!-- 引入当前页面的css -->
<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='front/macroData/index/css/macroData.css')}}"/>
<script type="text/javascript" src="{{url_for('static', filename='sys/js/jquery-2.0.0.min.js')}}"></script>
<script type="text/javascript" src="{{url_for('static', filename='sys/js/echarts.min.js')}}"></script>
<script type="text/javascript" src="{{url_for('static', filename='front/macroData/index/js/macroData.js')}}"></script>
{% endblock %}

<!-- 主内容 -->
{% block view_main %}
<!--  
<div>
	<input type="text" class="country"/>
	<button class="queryCountry">查询</button>
</div>
<div id="main" style="width: 800px;height:500px;"></div>
-->
<ul class="menu">
	<li class="li"><a href="{{url_for('viewManager.toGdp')}}">GDP数据</a></li>
	<li class="li">GDP数据</li>
	<li class="li">GDP数据</li>
	<li class="li">GDP数据</li>
	<li class="li">GDP数据</li>
</ul>	
	
	
	
{% endblock %}























































economy/templates/layout.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>主页</title>
<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='sys/css/sys.css')}}"/>
<script type="text/javascript" src="{{url_for('static', filename='sys/js/jquery-2.0.0.min.js')}}"></script>
<script type="text/javascript" src="{{url_for('static', filename='sys/js/layout.js')}}"></script>
{% block outRefer %}{% endblock %}
</head>
<body scroll="no">
	{% block view_header %}{% endblock %}
	{% block view_main %}{% endblock %}
	{% block view_footer %}{% endblock %}
</body>
</html>



















































economy/templates/test.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<h1>这是一个测试</h1>
</body>
</html>